// Dev-only: copies the self-hosted woff2 subsets used by the original site
// (Open Sans latin, Hind Siliguri bengali+latin; weights 400-700) into the theme.
import fs from "node:fs";
import path from "node:path";
const out = "../../wp-content/themes/shilperhaat/assets/fonts";
fs.mkdirSync(out, { recursive: true });
let css = "/* Generated by tools/theme-build/build-fonts.mjs — self-hosted, no external requests */\n";
const fams = [
  ["open-sans", "Open Sans", ["latin"]],
  ["hind-siliguri", "Hind Siliguri", ["bengali", "latin"]],
];
for (const [pkg, family, subsets] of fams) {
  for (const w of [400, 500, 600, 700]) {
    const srcCss = fs.readFileSync(`node_modules/@fontsource/${pkg}/${w}.css`, "utf8");
    for (const subset of subsets) {
      const re = new RegExp(`/\\* ${pkg}-${subset}-${w}-normal \\*/\\s*@font-face \\{[^}]*unicode-range: ([^;]+);`);
      const m = srcCss.match(re);
      const file = `${pkg}-${subset}-${w}-normal.woff2`;
      fs.copyFileSync(`node_modules/@fontsource/${pkg}/files/${file}`, path.join(out, file));
      css += `@font-face{font-family:"${family}";font-style:normal;font-display:swap;font-weight:${w};src:url(../fonts/${file}) format("woff2");unicode-range:${m[1]};}\n`;
    }
  }
}
fs.writeFileSync("../../wp-content/themes/shilperhaat/assets/css/fonts.css", css);
console.log("fonts ok");
