// Dev-only: bakes the Lucide icons used by the original site into inc/icons.php.
// Add names to ICONS and re-run when a later step needs another icon.
import fs from "node:fs";
const ICONS = {
  search: "search", "shopping-cart": "shopping-cart", menu: "menu", user: "user",
  package: "package", "chevron-down": "chevron-down", x: "x", phone: "phone",
  "help-circle": "circle-question-mark", info: "info", "message-circle": "message-circle",
  "book-open": "book-open", home: "house", "message-square": "message-square",
  "chevron-right": "chevron-right", "chevron-left": "chevron-left", mail: "mail", "map-pin": "map-pin",
  "arrow-right": "arrow-right", star: "star", quote: "quote", "check-circle": "circle-check",
  "x-circle": "circle-x", "alert-circle": "circle-alert",
  "sliders-horizontal": "sliders-horizontal", filter: "funnel", "zoom-in": "zoom-in", play: "play", check: "check",
  "trash-2": "trash-2", minus: "minus", plus: "plus", "shopping-bag": "shopping-bag", loader: "loader-circle",
  "chevron-up": "chevron-up", truck: "truck", clock: "clock", "refresh-cw": "refresh-cw", "x-circle-big": "circle-x",
};
let php = "<?php\n// Generated by tools/theme-build/build-icons.mjs (Lucide, ISC license). Do not edit by hand.\nif ( ! defined( 'ABSPATH' ) ) { exit; }\n\nfunction sh_icon_paths() {\n\treturn array(\n";
for (const [key, file] of Object.entries(ICONS)) {
  const svg = fs.readFileSync(`node_modules/lucide-static/icons/${file}.svg`, "utf8");
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").replace(/\s+/g, " ").trim();
  php += `\t\t'${key}' => '${inner.replace(/'/g, "\\'")}',\n`;
}
php += `\t);
}

/**
 * Inline Lucide icon (same geometry/stroke as lucide-react used by the original site).
 */
function sh_icon( $name, $size = 24, $style = '', $stroke_width = 2, $class = '' ) {
	$paths = sh_icon_paths();
	if ( ! isset( $paths[ $name ] ) ) {
		return '';
	}
	return sprintf(
		'<svg xmlns="http://www.w3.org/2000/svg" width="%1$s" height="%1$s" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="%2$s" stroke-linecap="round" stroke-linejoin="round"%3$s%4$s aria-hidden="true">%5$s</svg>',
		esc_attr( $size ),
		esc_attr( $stroke_width ),
		$style ? ' style="' . esc_attr( $style ) . '"' : '',
		$class ? ' class="' . esc_attr( $class ) . '"' : '',
		$paths[ $name ] // phpcs:ignore WordPress.Security.EscapeOutput
	);
}
`;
fs.writeFileSync("../../wp-content/themes/shilperhaat/inc/icons.php", php);
console.log("icons ok");
