// Dev-time: extracts the lucide icons used by the reference app into a PHP array (plugin/includes/icons.php).
const fs = require("fs"), path = require("path");
const ref = path.resolve(__dirname, "../reference-nextjs");
const lucide = process.argv[2]; // path to lucide-react package (from a reference install)
const used = new Set();
(function walk(d) {
  for (const f of fs.readdirSync(d, { withFileTypes: true })) {
    if (f.name === "node_modules" || f.name === ".next") continue;
    const p = path.join(d, f.name);
    if (f.isDirectory()) walk(p);
    else if (/\.tsx$/.test(f.name)) {
      const s = fs.readFileSync(p, "utf8");
      for (const m of s.matchAll(/import\s*\{([^}]*)\}\s*from\s*["']lucide-react["']/g))
        m[1].split(",").map(x => x.trim()).filter(Boolean).forEach(n => used.add(n.split(/\s+as\s+/)[0]));
    }
  }
})(ref);
const kebab = n => n.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/([A-Za-z])(\d)/g, "$1-$2").toLowerCase();
const out = {};
const idx = fs.readFileSync(path.join(lucide, "dist/esm/lucide-react.mjs"), "utf8");
const fileOf = {};
for (const m of idx.matchAll(/export \{([^}]*)\} from '\.\/icons\/([a-z0-9-]+)\.mjs'/g))
  for (const part of m[1].split(",")) { const mm = part.trim().match(/default as (\w+)/); if (mm) fileOf[mm[1]] = m[2]; }
for (const name of [...used].sort()) {
  const f = fileOf[name];
  if (!f) { console.error("missing icon", name); continue; }
  const src = fs.readFileSync(path.join(lucide, "dist/esm/icons", f + ".mjs"), "utf8");
  const m = src.match(/const __iconNode = (\[[\s\S]*?\]);\nconst /);
  if (!m) { console.error("no iconNode", name); continue; }
  const node = eval(m[1]);
  out[kebab(name)] = node.map(([tag, attrs]) => {
    const a = Object.entries(attrs).filter(([k]) => k !== "key").map(([k, v]) => `${k}="${v}"`).join(" ");
    return `<${tag} ${a}/>`;
  }).join("");
}
let php = "<?php\n// Generated by tools/gen-icons.js from lucide-react (ISC licence). Do not edit by hand.\ndefined( 'ABSPATH' ) || exit;\n\nreturn [\n";
for (const [k, v] of Object.entries(out)) php += `\t'${k}' => '${v.replace(/'/g, "\\'")}',\n`;
php += "];\n";
fs.writeFileSync(path.resolve(__dirname, "../wp-content/plugins/shilperhaat-cms/includes/icons.php"), php);
const js = "/* Generated by tools/gen-icons.js from lucide-react (ISC licence). Do not edit by hand. */\n(function(){var I=" + JSON.stringify(out) + ";\nwindow.ShIcon=function(n,s,st,c,x){x=x||{};if(!I[n])return'';return '<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"'+(s||24)+'\" height=\"'+(s||24)+'\" viewBox=\"0 0 24 24\" fill=\"'+(x.fill||'none')+'\" stroke=\"'+(x.stroke||'currentColor')+'\" stroke-width=\"'+(x['stroke-width']||2)+'\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-'+n+(c?' '+c:'')+'\" aria-hidden=\"true\"'+(st?' style=\"'+st+'\"':'')+'>'+I[n]+'</svg>';};})();\n";
fs.mkdirSync(path.resolve(__dirname, "../wp-content/themes/shilperhaat/assets/js"), { recursive: true });
fs.writeFileSync(path.resolve(__dirname, "../wp-content/themes/shilperhaat/assets/js/icons.js"), js);
fs.mkdirSync(path.resolve(__dirname, "../wp-content/plugins/shilperhaat-cms/admin/assets"), { recursive: true });
fs.writeFileSync(path.resolve(__dirname, "../wp-content/plugins/shilperhaat-cms/admin/assets/icons.js"), js);
console.log("icons:", Object.keys(out).length, "of", used.size);
